version: '3'
networks:
  network-delegation-diet:

services:
  nginx-delegation-diet:
     image: nginx:stable-alpine
     ports:
       - "8080:80"
     volumes:
      - ./app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
     depends_on:
       - php-fpm-delegation-diet
     networks:
       - network-delegation-diet
  php-fpm-delegation-diet:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/project
    networks:
      - network-delegation-diet
